### PR TITLE
issue #5: Chained Shoulds only fail when the last Should in the chain fails (quickfix)

### PR DESCRIPTION
**Pull request by c-mu**
moved verification of result before chaining
added test Fail on any failing chained Should

### CODE REVIEW

**Comment by c-mu** [comment]
I implemented the "nice fix". Please review carefully as I made some changes to the return values: instead of true/false, PShould now returns Passed/Failed if -test is used. When a should fails, I also added the assertion statement and stack trace to mimic the output of an exception (please see the commit message for more details on the changes). This additional info is also displayed when test cases expect a throw, which is somewhat counter intuitive.
Please let me know what you think. After all it's your baby.

**Comment by jonwagner** [comment]
Cool. At a glance it looks good, but I'll have to take a moment to wrap my head around it.

**Comment by jonwagner** [comment]
Hm...it looks like this loses the -test option, and it's a little chattier than I'd want the output to be. I do think that we can use this technique for chaining the output. I'll try to find some time to make the best of both worlds.

**Comment by c-mu** [comment]
It shouldn't lose the -test option. It does however no longer return true/false, but Passed/Failed. In addition, because the output is generated by PShould, it produces the exception like stacktraces also for the false positives, i.e. the testcases which are expected to fail. In your tests you worked around that by catching the exception in the test. BTW this almost made me miss a few issues where the test was throwing an (unexpected) exception. 
I thought about addressing the chattiness, but then again I would have tweaked the code to satisfy the test...

**Comment by c-mu** [comment]
Oh, I see... I missed something regarding -test. In the original implementation it supressed throwing the exception, thereby truncating the output. Translated to my implementation that would mean to also truncate the data collected in case of failure to just the status. In that regard, yes it's losing the purpose of -test.
May I propose another refactoring to address this? I'd like to see PShould not generating any output to the console at all, since how the results are reported is handled in PSate (console vs. NUnit file vs ...). So PShould should just create the testresult and pass it back to it's caller (PSate or PShould.Tests), where the result should be interpreted for generating output. Following that logic, -test (or something similar) should then be removed from PShould as well, since it would control the output which is already handled by PShould's caller. 
If you agree I'd create another changeset containing the necessary changes in PShould.

**Comment by c-mu** [comment]
I implemented the change proposed above. PShould still generates the verbose output (Testresult with Status, Assertion and Stacktrace in case of failure) to send down the pipe, resp. back to the caller, but only displays when specifying -test. PShould only throws in case of failure and not -test.

**Pull request closed without merging**
